"""adição get usuario by id e remover usuario

Revision ID: 2e145e014b31
Revises: 1d25e204c13d
Create Date: 2024-12-05 10:28:16.670158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e145e014b31'
down_revision: Union[str, None] = '1d25e204c13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
