"""Add endereco_entrega to pedido

Revision ID: 4ba16260823c
Revises: 61bb7ee67d94
Create Date: 2024-12-12 17:57:23.957634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba16260823c'
down_revision: Union[str, None] = '61bb7ee67d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
