"""retorno ProdutoSimples em put produtos

Revision ID: 4cef8b7cada2
Revises: 2e145e014b31
Create Date: 2024-12-06 17:42:25.387295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cef8b7cada2'
down_revision: Union[str, None] = '2e145e014b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
