"""Add endereco_entrega to pedido

Revision ID: 61bb7ee67d94
Revises: c391892e148a
Create Date: 2024-12-12 17:56:59.595720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bb7ee67d94'
down_revision: Union[str, None] = 'c391892e148a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comprador_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_pedido_usuario', type_='foreignkey')
        batch_op.create_foreign_key('fk_pedido_vendedor', 'usuario', ['vendedor_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_comprador', 'usuario', ['comprador_id'], ['id'])
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('local_entrega')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_entrega', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_pedido_comprador', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_vendedor', type_='foreignkey')
        batch_op.create_foreign_key('fk_pedido_usuario', 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('comprador_id')
        batch_op.drop_column('vendedor_id')
        batch_op.drop_column('endereco_entrega')

    # ### end Alembic commands ###
