"""fix funcoes e rotas de pedidos

Revision ID: e8b00b3fcc4e
Revises: 4ba16260823c
Create Date: 2024-12-12 18:15:30.675987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b00b3fcc4e'
down_revision: Union[str, None] = '4ba16260823c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
