"""fixed issues; add: view de minhas vendas e minhas compras

Revision ID: be380417607f
Revises: e8b00b3fcc4e
Create Date: 2025-01-08 14:32:31.138046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be380417607f'
down_revision: Union[str, None] = 'e8b00b3fcc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
