"""add: hash/token provider; fix: atuenticação signup

Revision ID: dc4b0000fe4b
Revises: be380417607f
Create Date: 2025-01-08 15:14:50.992570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4b0000fe4b'
down_revision: Union[str, None] = 'be380417607f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
