"""add: rota de visualização do usuario

Revision ID: dffc76c26525
Revises: dc4b0000fe4b
Create Date: 2025-01-09 11:46:01.087168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffc76c26525'
down_revision: Union[str, None] = 'dc4b0000fe4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
